### PR TITLE
Unbalanced

### PR DESCRIPTION
**Pull request by Gameri1**
I find this mod a bit unbalanced. I feel like being able to mine for hours without risking death by mobs is a bit too good when you just start a world. I believe it should be harder to get into those biomes with a custom flint and steel for example that is a bit more valuable.

### CODE REVIEW

**Comment by kwpugh** [comment]
Sorry you feel that way, but I like it the way I designed it.  Feel free to make a datapack mining dimension mod of your own and to your liking.

Regards

**Comment by JackGlobetrotter** [comment]
> Sorry you feel that way, but I like it the way I designed it. Feel free to make a datapack mining dimension mod of your own and to your liking.
> 
> Regards

sorry to bother you, i tried to modify your mod for my own use to add monsters back to caving dimension, but i am not able to find where they have been disabled/need to be added in, would you be able yo point me in the right direction? I really would appreciate your help, furthermore this mod is great, i enjoy playing it a lot, thanks for your work !

**Comment by kwpugh** [comment]
its two parts:  1) the dimension json uses mushroom island biome, which doesn't allow spawning of mods except for placed spawners and 2) the dimension type has a flag for disabling mobs.

**Comment by kwpugh** [comment]
Sorry, the #2 is in the noise settings

Screen Shot 2022-02-04 at 8 46 37 AM

**Comment by kwpugh** [comment]
That said, some mods like Mythic Mounts and others don't respect the mojang system and spawn in everything, but at least it rids the dimension of all the vanilla mods.

**Comment by JackGlobetrotter** [comment]
> Sorry, the #2 is in the noise settings
> 
> Screen Shot 2022-02-04 at 8 46 37 AM

thanks a lot for your help, i noticed that "disable_mob_generation" is set to true for all dimensions and does not seem to affect mob spawning?

**Comment by kwpugh** [comment]
yeah, I guess that is why mojang considers the dimensions via datapack "experimental"

**Comment by kwpugh** [comment]
are you trying to just change the portal blocks and/or starters?

**Comment by JackGlobetrotter** [comment]
> are you trying to just change the portal blocks and/or starters?

i am just trying to have mobs spawn in caving dim, found the solution:
changed biome_type to plains and it worked like a charm
i forked the repo and changed it, for anyone interested

**Comment by kwpugh** [comment]
that will do it, the mushroom biome suppresses mob spawn.  It will likely get a LOT of spawns as plains in the big caves, good luck.  With mob spawns, I don't really see the point of the dim, you can just mine in the overworld.

**Comment by JackGlobetrotter** [comment]
> that will do it, the mushroom biome suppresses mob spawn. It will likely get a LOT of spawns as plains in the big caves, good luck. With mob spawns, I don't really see the point of the dim, you can just mine in the overworld.

would you be fine with me making this an configurable option and making a PR ?

**Comment by kwpugh** [comment]
I don't do PR's.   How would you make a value in the JSON configurable?

**Comment by JackGlobetrotter** [comment]
well, i did not think that through.... you are right. 
Anyway, thanks a lot for your help :)

**Comment by kwpugh** [comment]
I would think you would have to dynamically re-generate the entire JSON

**Comment by JackGlobetrotter** [comment]
i think there could be jsons for both variants and a switch just before registering the dims, maybe in MiningDimsRegistry()

**Comment by kwpugh** [comment]
a datapack would make more sense if someone wanted different dim generation

**Comment by kwpugh** [comment]
then they could tailor whatever they want

**Comment by JackGlobetrotter** [comment]
you may be right, tbh i have never worked with datapacks before

**Comment by kwpugh** [comment]
data packs are becoming the preferred method for mod customization these days, as they require little code changes to support.
  And they are so easy to make.

**Comment by JackGlobetrotter** [comment]
i will have a look into that, but for now the mod works fine for me as is

**Pull request closed without merging**
